# Generated by Django 4.2.4 on 2023-08-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRedirecionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url_curta', models.CharField(max_length=10, unique=True)),
                ('url_destino', models.URLField()),
                ('clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link de Redirecionamento',
                'verbose_name_plural': 'Links de Redirecionamento',
                'ordering': ['title'],
            },
        ),
    ]
